sudo: required
services:
  - docker
script:
  - docker build -t practica .
after_success:
  - docker login -u $DOCKER.USER -p $DOCKER.PASSWORD
  - docker tag practica $DOCKER.USER/practica
  - docker push $DOCKER.USER/practica

